// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbpl3g3L85lHC4ZjlOQGWfGl8zlL8z2yc',
    appId: '1:211317508595:web:c30e2cb16d02dfea57aa86',
    messagingSenderId: '211317508595',
    projectId: 'zizu-f8ae2',
    authDomain: 'zizu-f8ae2.firebaseapp.com',
    storageBucket: 'zizu-f8ae2.appspot.com',
    measurementId: 'G-TM9JKBMWCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmYsGVBuJLOIQWIF82nc9NdvTFl6JWSfM',
    appId: '1:211317508595:android:73e53238cd6b399b57aa86',
    messagingSenderId: '211317508595',
    projectId: 'zizu-f8ae2',
    storageBucket: 'zizu-f8ae2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHCDANrQzI9o7mNidndVzX2lO9mLtX42g',
    appId: '1:211317508595:ios:cf38bd1a452e1bfb57aa86',
    messagingSenderId: '211317508595',
    projectId: 'zizu-f8ae2',
    storageBucket: 'zizu-f8ae2.appspot.com',
    iosClientId: '211317508595-vf2sl362k14etkat7i8gpa6gfjru57kj.apps.googleusercontent.com',
    iosBundleId: 'flutter.flow',
  );
}
